services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: devops-app
    expose:
      - "5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASSWORD: devpass
    networks:
      - front_net
      - back_net

  nginx:
    image: nginx:1.27-alpine
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - front_net

  db:
    image: postgres:16
    container_name: devops-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net

networks:
  front_net:
  back_net:

volumes:
  db_data:
  nginx_logs:
