services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: devops-app
    expose:
      - "5000"
    env_file:
      - .env
    networks:
      - front_net
      - back_net

  nginx:
    image: nginx:1.27-alpine
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - front_net

  db:
    image: postgres:16
    container_name: devops-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net

  seed_runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: devops-seed
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app/app
    command: ["python", "-m", "app.seed.run_seed"]
    volumes:
      - seed_output:/seed_output
    networks:
      - back_net
    restart: "no"

  migration_runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: devops-migrations
    depends_on:
      - db
    working_dir: /app/app
    command: ["python", "-m", "migrations.run_migrations"]
    networks:
      - back_net
    restart: "no"

networks:
  front_net:
  back_net:

volumes:
  db_data:
  nginx_logs:
  seed_output: