name: CI

on:
  push:
    branches: ["main", "master", "*"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build test image (runs pytest)
        run: |
          docker build \
            --target test \
            -t ghcr.io/${{ github.repository_owner }}/devops-app-test:${{ github.sha }} \
            .

      - name: Build final image
        run: |
          docker build \
            --target final \
            -t ghcr.io/${{ github.repository_owner }}/devops-app:${{ github.sha }} \
            .

#      - name: Push final image
#        run: |
#          docker push ghcr.io/${{ github.repository_owner }}/devops-app:${{ github.sha }}

#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v3
#        with:
#          languages: python

#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v3